version: '3.8'

services:
  sales_api:
    container_name: sales_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www
    networks:
      - sd_network
    environment:
      - DB_HOST=sd_db_sales
      - DB_DATABASE=sales_db
      - DB_USERNAME=root
      - DB_PASSWORD=3312
    restart: unless-stopped

  sales_nginx:
    container_name: sales_nginx
    image: nginx:alpine
    ports:
      - "8004:80"
    volumes:
      - ./api:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sales_api
    networks:
      - sd_network
    restart: unless-stopped

networks:
  sd_network:
    external: true
