services:
  config_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - sd_network

  config_nginx:
    image: nginx:alpine
    container_name: config_nginx
    restart: unless-stopped
    ports:
      - "8007:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sd_network
    depends_on:
      - config_api

networks:
  sd_network:
    external: true
