version: '3.8'

services:
  hr_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    networks:
      - sd_network

  hr_nginx:
    image: nginx:alpine
    container_name: hr_nginx
    restart: unless-stopped
    ports:
      - "8006:80"
    volumes:
      - ./api:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hr_api
    networks:
      - sd_network

networks:
  sd_network:
    external: true
