services:
  gateway_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - sd_network

  gateway_nginx:
    image: nginx:alpine
    container_name: gateway_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sd_network
    depends_on:
      - gateway_api

networks:
  sd_network:
    external: true
