version: '3.8'

services:
  # Servicio PHP-FPM de Auth API
  auth_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - sd_network
    environment:
      - DB_HOST=sd_db_auth
      - DB_DATABASE=auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=3312
      - DB_READ_HOST=sd_db_auth_replica

  # Nginx para servir la API
  auth_nginx:
    image: nginx:alpine
    container_name: auth_nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sd_network
    depends_on:
      - auth_api

networks:
  sd_network:
    external: true
